class ButtonStrings:
    BOT_STATUS = "👥 آمار ربات 👥"
    CHANNEL_SETTING_PANEL = "📍 بخش چنل 📍"
    ADMIN_SETTING_PANEL = "🪄 بخش ادمین 🪄"
    USER_SETTING_PANEL = "🪩 بخش کاربر 🪩"
    SENDER_PANEL = "📣 پیام رسانی 📣"
    ADD_ADMIN = "💥 افزودن ادمین 💥"
    REMOVE_ADMIN = "🫧 حذف ادمین 🫧"
    ADMINS_LIST = "❄️ لیست ادمین ها ❄️"
    ADD_CHANNEL = "🧮 افزودن چنل 🧮"
    REMOVE_CHANNEL = "🖇 حذف چنل 🖇"
    CHANELLS_LIST = "🗂 لیست چنل ها 🗂"
    FORWARD_TO_ALL = "📎 فوروارد همگانی"
    SEND_TO_ALL = "🖇 پیام همگانی"
    BACK_TO_ADMIN_PANEL = "🔙 برگشت 🔙"
    CLOSE_ADMIN_PANEL = "❌ بستن پنل مدیر ❌"
    CHANCEL_PROCEC = "❌ کنسل کردن ❌"